# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'real_quick' do
  use_frameworks!

  # Pods for real_quick
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crash'

end
